version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "testapp1"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-py10bcmv10ah"
s3_prefix = "testapp1"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["HelloWorldFunction=094715509311.dkr.ecr.us-east-1.amazonaws.com/testapp14acbe16e/helloworldfunction19d43fc4repo"]
